author: "Sander Lepik <sander@lepik.eu>"
category: "http"
summary: "Send presence notifications to external HTTP server"
home: "https://github.com/sander85/mod_http_presence"
url: "git@github.com:sander85/mod_http_presence.git"
